export type AlertSeverity = 'low' | 'medium' | 'high' | 'critical';

export interface Alert {
  id: string;
  timestamp: Date;
  type: string;
  description: string;
  severity: AlertSeverity;
  imageUrl?: string;
  status: 'active' | 'resolved' | 'dismissed';
  confidence?: number;
}

export interface DetectionResult {
  isSuspicious: boolean;
  threatLevel: AlertSeverity;
  description: string;
  confidence?: number;
  detectedObjects: {
    label: string;
    x: number;
    y: number;
    type: 'friendly' | 'suspicious' | 'armed';
    confidence?: number;
  }[];
  visualCues?: string[];
  movementPattern?: 'steady' | 'erratic' | 'stealthy' | 'aggressive';
  temperature?: number;
}

export interface SystemLog {
  id: string;
  timestamp: Date;
  event: string;
  type: 'info' | 'warning' | 'error' | 'success';
}

export interface Personnel {
  id: string;
  name: string;
  rank: string;
  clearance: 'LEVEL_1' | 'LEVEL_2' | 'LEVEL_3' | 'LEVEL_4' | 'LEVEL_5';
  status: 'ACTIVE' | 'OFF_DUTY' | 'DEPLOYED' | 'INACTIVE';
  lastSeen?: string;
  photo?: string;
}

export interface WeatherInfo {
  temp: number;
  condition: string;
  humidity: number;
  windSpeed: number;
  visibility: string;
}

export interface ChatMessage {
  id: string;
  timestamp: Date;
  sender: string;
  content: string;
  type: 'system' | 'user' | 'unit';
  isAutoGenerated?: boolean;
  imageUrl?: string;
}

export interface TacticalEntity {
  id: string;
  type: 'friendly' | 'suspicious' | 'armed';
  x: number; // 0-100 percentage
  y: number; // 0-100 percentage
  label: string;
  hasId: boolean;
  detectedBy: 'GPS' | 'AI_VISION';
  visualCues?: string[];
  movementPattern?: 'steady' | 'erratic' | 'stealthy' | 'aggressive';
  temperature?: number;
  confidence?: number;
}

declare global {
  interface Window {
    aistudio: {
      hasSelectedApiKey: () => Promise<boolean>;
      openSelectKey: () => Promise<void>;
    };
  }
}
