export type AlertSeverity = 'low' | 'medium' | 'high' | 'critical';

export interface Alert {
  id: string;
  timestamp: Date;
  type: string;
  description: string;
  severity: AlertSeverity;
  imageUrl?: string;
  status: 'active' | 'resolved' | 'dismissed';
}

export interface DetectionResult {
  isSuspicious: boolean;
  threatLevel: AlertSeverity;
  description: string;
  detectedObjects: string[];
  visualCues?: string[];
  movementPattern?: 'steady' | 'erratic' | 'stealthy' | 'aggressive';
  temperature?: number;
}

export interface SystemLog {
  id: string;
  timestamp: Date;
  event: string;
  type: 'info' | 'warning' | 'error' | 'success';
}

export interface Personnel {
  id: string;
  name: string;
  rank: string;
  status: 'active' | 'on-leave' | 'deployed';
  location: string;
}

export interface WeatherInfo {
  temp: number;
  condition: string;
  humidity: number;
  windSpeed: number;
  visibility: string;
}

export interface ChatMessage {
  id: string;
  timestamp: Date;
  sender: string;
  content: string;
  type: 'system' | 'user' | 'unit';
  isAutoGenerated?: boolean;
}

export interface TacticalEntity {
  id: string;
  type: 'friendly' | 'suspicious' | 'armed';
  x: number; // 0-100 percentage
  y: number; // 0-100 percentage
  label: string;
  hasId: boolean;
  detectedBy: 'GPS' | 'AI_VISION';
  visualCues?: string[];
  movementPattern?: 'steady' | 'erratic' | 'stealthy' | 'aggressive';
  temperature?: number;
}
